#!/bin/bash

function check_case ()
{
    if [ "$1" == "-l" ]
    then
        case="lowercase"
    elif [ "$1" == "-u" ]
    then
        case="uppercase"
    elif [ -z $1 ]
    then
        error "Not enough arguments"
    else
        pattern="$1"
    fi
}

function error ()
{
    if [ -z "$1" ]
    then
        echo "Bad parameter"
    else
        echo $1
    fi
    print_help
}

function print_help ()
{
    echo "Usage:"
    echo "modify [-r] [-l|-u] <dir/file names...>"
    echo "modify [-r] <sed pattern> <dir/file names...>"
    echo "modify [-h]"
    exit
}

recursive="false"
if [ "$1" == "-h" ]
then
    print_help
fi
if [ "$1" == "-r" ]
then
    recursive="true"
    shift
else
    recursive="false"
fi
check_case "$1"
shift
if [ -z "$1" ]
then
    error "You need to provide at last one filename"
else
    for fullpath in "$@"
    do
        filename=$(basename "$fullpath")
        filepath=$(dirname "$fullpath")
        echo "$filename"
        echo "filepath: $filepath"
        if [ "$pattern" != "" ]
        then
            mv "$fullpath" "$filepath/`echo $filename | sed $pattern`"
            exit
        fi
        if [ "$case" == "uppercase" ]
        then
            mv "$fullpath" "$filepath/${filename^^}"
            else
                mv "$fullpath" "$filepath/${filename,,}"
            fi
    done
fi