#!/bin/bash

./modify -h
echo "---------------"
./modify -u "file 1"
echo "---------------"
./modify -l "FILE 1"
echo "---------------"
./modify "s/\([a-z]*\).*/\1/" "file 1" # deletes other words in filename
echo "---------------"
