#!/bin/bash

function check_case ()
{
    if [ "$1" == "-l" ]
    then
        case="lowercase"
    elif [ "$1" == "-u" ]
    then
        case="uppercase"
    else
        bad_param
    fi
}

function bad_param ()
{
    echo "Bad parameter"
    exit
}

function print_help ()
{
    echo "Here will be help"
    exit
}

if [ "$1" == "-h" ]
then
    print_help
fi
if [ "$1" == "-r" ]
then
    recursive=1
fi
if [ "$recursive" == "1" ]
then
    check_case "$2"
else
    check_case "$1"
fi

echo "case: $case"
echo "recursive: $recursive"

