touch "file 1"
touch "file 2"
mkdir "folder 1"
mkdir "folder 2"
touch "folder 2/file inside 1"
touch "folder 2/file inside 2"
touch "folder 1/file inside 1"
touch "folder 1/file inside 2"
mkdir "folder 1/folder inside/"
mkdir "folder 1/folder inside/file inside deep 1"
mkdir "folder 1/folder inside/file inside deep 2"